// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: transactions.sql

package db

import (
	"context"
	"database/sql"
)

const createTransactions = `-- name: CreateTransactions :one
INSERT INTO transactions (order_id, merchant_id, payment_method, amount, change_amount, payment_status)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING transaction_id, order_id, merchant_id, payment_method, amount, change_amount, payment_status, created_at, updated_at, deleted_at
`

type CreateTransactionsParams struct {
	OrderID       int32         `json:"order_id"`
	MerchantID    int32         `json:"merchant_id"`
	PaymentMethod string        `json:"payment_method"`
	Amount        int32         `json:"amount"`
	ChangeAmount  sql.NullInt32 `json:"change_amount"`
	PaymentStatus string        `json:"payment_status"`
}

func (q *Queries) CreateTransactions(ctx context.Context, arg CreateTransactionsParams) (*Transaction, error) {
	row := q.db.QueryRowContext(ctx, createTransactions,
		arg.OrderID,
		arg.MerchantID,
		arg.PaymentMethod,
		arg.Amount,
		arg.ChangeAmount,
		arg.PaymentStatus,
	)
	var i Transaction
	err := row.Scan(
		&i.TransactionID,
		&i.OrderID,
		&i.MerchantID,
		&i.PaymentMethod,
		&i.Amount,
		&i.ChangeAmount,
		&i.PaymentStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const deleteAllPermanentTransactions = `-- name: DeleteAllPermanentTransactions :exec
DELETE FROM transactions
WHERE
    deleted_at IS NOT NULL
`

// Delete All Trashed Transaction Permanently
func (q *Queries) DeleteAllPermanentTransactions(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllPermanentTransactions)
	return err
}

const deleteTransactionPermanently = `-- name: DeleteTransactionPermanently :exec
DELETE FROM transactions WHERE transaction_id = $1 AND deleted_at IS NOT NULL
`

// Delete Transaction Permanently
func (q *Queries) DeleteTransactionPermanently(ctx context.Context, transactionID int32) error {
	_, err := q.db.ExecContext(ctx, deleteTransactionPermanently, transactionID)
	return err
}

const getTransactionByID = `-- name: GetTransactionByID :one
SELECT transaction_id, order_id, merchant_id, payment_method, amount, change_amount, payment_status, created_at, updated_at, deleted_at
FROM transactions
WHERE transaction_id = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetTransactionByID(ctx context.Context, transactionID int32) (*Transaction, error) {
	row := q.db.QueryRowContext(ctx, getTransactionByID, transactionID)
	var i Transaction
	err := row.Scan(
		&i.TransactionID,
		&i.OrderID,
		&i.MerchantID,
		&i.PaymentMethod,
		&i.Amount,
		&i.ChangeAmount,
		&i.PaymentStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const getTransactionByMerchant = `-- name: GetTransactionByMerchant :many
SELECT
    transaction_id, order_id, merchant_id, payment_method, amount, change_amount, payment_status, created_at, updated_at, deleted_at,
    COUNT(*) OVER() AS total_count
FROM transactions
WHERE deleted_at IS NULL
  AND ($1::TEXT IS NULL OR payment_method ILIKE '%' || $1 || '%' OR payment_status ILIKE '%' || $1 || '%')
  AND ($2::INT IS NULL OR merchant_id = $2)
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type GetTransactionByMerchantParams struct {
	Column1 string `json:"column_1"`
	Column2 int32  `json:"column_2"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

type GetTransactionByMerchantRow struct {
	TransactionID int32         `json:"transaction_id"`
	OrderID       int32         `json:"order_id"`
	MerchantID    int32         `json:"merchant_id"`
	PaymentMethod string        `json:"payment_method"`
	Amount        int32         `json:"amount"`
	ChangeAmount  sql.NullInt32 `json:"change_amount"`
	PaymentStatus string        `json:"payment_status"`
	CreatedAt     sql.NullTime  `json:"created_at"`
	UpdatedAt     sql.NullTime  `json:"updated_at"`
	DeletedAt     sql.NullTime  `json:"deleted_at"`
	TotalCount    int64         `json:"total_count"`
}

func (q *Queries) GetTransactionByMerchant(ctx context.Context, arg GetTransactionByMerchantParams) ([]*GetTransactionByMerchantRow, error) {
	rows, err := q.db.QueryContext(ctx, getTransactionByMerchant,
		arg.Column1,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*GetTransactionByMerchantRow
	for rows.Next() {
		var i GetTransactionByMerchantRow
		if err := rows.Scan(
			&i.TransactionID,
			&i.OrderID,
			&i.MerchantID,
			&i.PaymentMethod,
			&i.Amount,
			&i.ChangeAmount,
			&i.PaymentStatus,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionByOrderID = `-- name: GetTransactionByOrderID :one
SELECT transaction_id, order_id, merchant_id, payment_method, amount, change_amount, payment_status, created_at, updated_at, deleted_at
FROM transactions
WHERE order_id = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetTransactionByOrderID(ctx context.Context, orderID int32) (*Transaction, error) {
	row := q.db.QueryRowContext(ctx, getTransactionByOrderID, orderID)
	var i Transaction
	err := row.Scan(
		&i.TransactionID,
		&i.OrderID,
		&i.MerchantID,
		&i.PaymentMethod,
		&i.Amount,
		&i.ChangeAmount,
		&i.PaymentStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const getTransactions = `-- name: GetTransactions :many
SELECT
    transaction_id, order_id, merchant_id, payment_method, amount, change_amount, payment_status, created_at, updated_at, deleted_at,
    COUNT(*) OVER() AS total_count
FROM transactions
WHERE deleted_at IS NULL
  AND ($1::TEXT IS NULL OR payment_method ILIKE '%' || $1 || '%' OR payment_status ILIKE '%' || $1 || '%')
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetTransactionsParams struct {
	Column1 string `json:"column_1"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

type GetTransactionsRow struct {
	TransactionID int32         `json:"transaction_id"`
	OrderID       int32         `json:"order_id"`
	MerchantID    int32         `json:"merchant_id"`
	PaymentMethod string        `json:"payment_method"`
	Amount        int32         `json:"amount"`
	ChangeAmount  sql.NullInt32 `json:"change_amount"`
	PaymentStatus string        `json:"payment_status"`
	CreatedAt     sql.NullTime  `json:"created_at"`
	UpdatedAt     sql.NullTime  `json:"updated_at"`
	DeletedAt     sql.NullTime  `json:"deleted_at"`
	TotalCount    int64         `json:"total_count"`
}

func (q *Queries) GetTransactions(ctx context.Context, arg GetTransactionsParams) ([]*GetTransactionsRow, error) {
	rows, err := q.db.QueryContext(ctx, getTransactions, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*GetTransactionsRow
	for rows.Next() {
		var i GetTransactionsRow
		if err := rows.Scan(
			&i.TransactionID,
			&i.OrderID,
			&i.MerchantID,
			&i.PaymentMethod,
			&i.Amount,
			&i.ChangeAmount,
			&i.PaymentStatus,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionsActive = `-- name: GetTransactionsActive :many
SELECT
    transaction_id, order_id, merchant_id, payment_method, amount, change_amount, payment_status, created_at, updated_at, deleted_at,
    COUNT(*) OVER() AS total_count
FROM transactions
WHERE deleted_at IS NULL
AND ($1::TEXT IS NULL OR payment_method ILIKE '%' || $1 || '%' OR payment_status ILIKE '%' || $1 || '%')
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetTransactionsActiveParams struct {
	Column1 string `json:"column_1"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

type GetTransactionsActiveRow struct {
	TransactionID int32         `json:"transaction_id"`
	OrderID       int32         `json:"order_id"`
	MerchantID    int32         `json:"merchant_id"`
	PaymentMethod string        `json:"payment_method"`
	Amount        int32         `json:"amount"`
	ChangeAmount  sql.NullInt32 `json:"change_amount"`
	PaymentStatus string        `json:"payment_status"`
	CreatedAt     sql.NullTime  `json:"created_at"`
	UpdatedAt     sql.NullTime  `json:"updated_at"`
	DeletedAt     sql.NullTime  `json:"deleted_at"`
	TotalCount    int64         `json:"total_count"`
}

// Get Active Transactions with Pagination and Total Count
func (q *Queries) GetTransactionsActive(ctx context.Context, arg GetTransactionsActiveParams) ([]*GetTransactionsActiveRow, error) {
	rows, err := q.db.QueryContext(ctx, getTransactionsActive, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*GetTransactionsActiveRow
	for rows.Next() {
		var i GetTransactionsActiveRow
		if err := rows.Scan(
			&i.TransactionID,
			&i.OrderID,
			&i.MerchantID,
			&i.PaymentMethod,
			&i.Amount,
			&i.ChangeAmount,
			&i.PaymentStatus,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionsTrashed = `-- name: GetTransactionsTrashed :many
SELECT
    transaction_id, order_id, merchant_id, payment_method, amount, change_amount, payment_status, created_at, updated_at, deleted_at,
    COUNT(*) OVER() AS total_count
FROM transactions
WHERE deleted_at IS NOT NULL
AND ($1::TEXT IS NULL OR payment_method ILIKE '%' || $1 || '%' OR payment_status ILIKE '%' || $1 || '%')
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetTransactionsTrashedParams struct {
	Column1 string `json:"column_1"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

type GetTransactionsTrashedRow struct {
	TransactionID int32         `json:"transaction_id"`
	OrderID       int32         `json:"order_id"`
	MerchantID    int32         `json:"merchant_id"`
	PaymentMethod string        `json:"payment_method"`
	Amount        int32         `json:"amount"`
	ChangeAmount  sql.NullInt32 `json:"change_amount"`
	PaymentStatus string        `json:"payment_status"`
	CreatedAt     sql.NullTime  `json:"created_at"`
	UpdatedAt     sql.NullTime  `json:"updated_at"`
	DeletedAt     sql.NullTime  `json:"deleted_at"`
	TotalCount    int64         `json:"total_count"`
}

// Get Trashed Transactions with Pagination and Total Count
func (q *Queries) GetTransactionsTrashed(ctx context.Context, arg GetTransactionsTrashedParams) ([]*GetTransactionsTrashedRow, error) {
	rows, err := q.db.QueryContext(ctx, getTransactionsTrashed, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*GetTransactionsTrashedRow
	for rows.Next() {
		var i GetTransactionsTrashedRow
		if err := rows.Scan(
			&i.TransactionID,
			&i.OrderID,
			&i.MerchantID,
			&i.PaymentMethod,
			&i.Amount,
			&i.ChangeAmount,
			&i.PaymentStatus,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreAllTransactions = `-- name: RestoreAllTransactions :exec
UPDATE transactions
SET
    deleted_at = NULL
WHERE
    deleted_at IS NOT NULL
`

// Restore All Trashed Transaction
func (q *Queries) RestoreAllTransactions(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, restoreAllTransactions)
	return err
}

const restoreTransaction = `-- name: RestoreTransaction :one
UPDATE transactions
SET
    deleted_at = NULL
WHERE
    transaction_id = $1
    AND deleted_at IS NOT NULL
  RETURNING transaction_id, order_id, merchant_id, payment_method, amount, change_amount, payment_status, created_at, updated_at, deleted_at
`

// Restore Trashed Transaction
func (q *Queries) RestoreTransaction(ctx context.Context, transactionID int32) (*Transaction, error) {
	row := q.db.QueryRowContext(ctx, restoreTransaction, transactionID)
	var i Transaction
	err := row.Scan(
		&i.TransactionID,
		&i.OrderID,
		&i.MerchantID,
		&i.PaymentMethod,
		&i.Amount,
		&i.ChangeAmount,
		&i.PaymentStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const trashTransaction = `-- name: TrashTransaction :one
UPDATE transactions
SET
    deleted_at = current_timestamp
WHERE
    transaction_id = $1
    AND deleted_at IS NULL
    RETURNING transaction_id, order_id, merchant_id, payment_method, amount, change_amount, payment_status, created_at, updated_at, deleted_at
`

// Trash Transaction
func (q *Queries) TrashTransaction(ctx context.Context, transactionID int32) (*Transaction, error) {
	row := q.db.QueryRowContext(ctx, trashTransaction, transactionID)
	var i Transaction
	err := row.Scan(
		&i.TransactionID,
		&i.OrderID,
		&i.MerchantID,
		&i.PaymentMethod,
		&i.Amount,
		&i.ChangeAmount,
		&i.PaymentStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const updateTransaction = `-- name: UpdateTransaction :one
UPDATE transactions
SET merchant_id = $2,
    payment_method = $3,
    amount = $4,
    change_amount = $5,
    payment_status = $6,
    order_id = $7,
    updated_at = CURRENT_TIMESTAMP
WHERE transaction_id = $1
  AND deleted_at IS NULL
RETURNING transaction_id, order_id, merchant_id, payment_method, amount, change_amount, payment_status, created_at, updated_at, deleted_at
`

type UpdateTransactionParams struct {
	TransactionID int32         `json:"transaction_id"`
	MerchantID    int32         `json:"merchant_id"`
	PaymentMethod string        `json:"payment_method"`
	Amount        int32         `json:"amount"`
	ChangeAmount  sql.NullInt32 `json:"change_amount"`
	PaymentStatus string        `json:"payment_status"`
	OrderID       int32         `json:"order_id"`
}

func (q *Queries) UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (*Transaction, error) {
	row := q.db.QueryRowContext(ctx, updateTransaction,
		arg.TransactionID,
		arg.MerchantID,
		arg.PaymentMethod,
		arg.Amount,
		arg.ChangeAmount,
		arg.PaymentStatus,
		arg.OrderID,
	)
	var i Transaction
	err := row.Scan(
		&i.TransactionID,
		&i.OrderID,
		&i.MerchantID,
		&i.PaymentMethod,
		&i.Amount,
		&i.ChangeAmount,
		&i.PaymentStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}
